development:
  adapter: postgresql
  database: intercom_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: intercom_test
  pool: 5
  timeout: 5000

# production:
#   adapter: postgresql
#   database: db/production.postgresql
#   pool: 5
#   timeout: 5000
